### PR TITLE
Autoloading classes and adding a dependency free plugin loader

### PR DESCRIPTION
**Pull request by mrgrain**
Added the theme bootstrap file to composer autoload section.
Thus this package can be truly used a dependency.

Fix for issue #102

### CODE REVIEW

**Comment by mrgrain** [comment]
I am sorry, this doesn't work out as easy as I thought it would. I'll look into it and open the PR again.

**Comment by mrgrain** [comment]
As pointed out in issue #102, the current plugin loader depends on the file path to the package. This is perfectly fine for most cases, but will break the workflow when using more sophisticated boilerplates like [Bedrock](https://github.com/roots/bedrock).

This PR fixes those problems by
- adding the classes to composer's classmap [1](https://github.com/oncletom/wp-less/pull/103/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R8)
- adding a new PluginLoader wrapper class [2](https://github.com/oncletom/wp-less/pull/103/files#diff-d9dbfded7597e92deb462a36dd21304bR1)
- and removing the dependency on the packages file path [3](https://github.com/oncletom/wp-less/pull/103/files#diff-571000d807cc1111b499a5aa3550b79aR42)

Nothing changes if this package is used...
- as a plugin (just install it)
- by a theme including `bootstrap-for-theme.php`

However it will provide a new option for other plugins or themes bundling the package. Instead of including `bootstrap-for-theme.php`, they might now rely on composers autloader and kickstart the plugin with a simple dependency free method (use of the closure is optional):
```php
$WPLessPlugin = \WPLessPluginLoader::load(function(WPLessPlugin ) {
    // they might add some actions here
    // add_action('after_setup_theme', array($WPLessPlugin, 'install'));
});
```
There's also a even more simple helper:
```php
$WPLessPlugin = \WPLessPluginLoader::getInstance($callable);
```
will fetch an existing instance of the plugin or create one.

-----

Those changes are tested in the listed use cases. Please let me know if I did oversee something. Any thoughts?

**Comment by oncletom** [comment]
What if the plugin is installed outside of composer, from the wp-plugins repository for instance?

**Comment by mrgrain** [comment]
Hi @oncletom, thanks for your question. Nothing will changes if used as a plugin. The new `WPLessPluginLoader` class will handle all the required file loading. It serves as a wrapper for `WPPluginToolkitPlugin::create` and mainly encapsulates the file path.

**Comment by oncletom** [comment]
OK i see your point!

I initially created `WPPluginToolkitPlugin` to share it across multiple plugin I would author. Sadly WordPress plugins SVN system does not allow submodules so it forced me to statically vendor this class.

So to be honest, if could totally be "de-abstracted" or worked out differently if that serves your proposal. Feel free to make the additional changes in a subsequent PR if needed :-)

Thanks again for your contribution!

**Pull request merged**
