### PR TITLE
Allow edit .less files with theme editor

### PR DESCRIPTION
**Pull request by pravdomil**
Self explaining.

_note: only top level .less files can be edited_

### CODE REVIEW

**Comment by pravdomil** [comment]
Please merge or reject this pull request.

**Comment by oncletom** [comment]
Thanks @pravdomil and sorry for the delay :-)

**Comment by pravdomil** [comment]
Great, do you think that you can push the changes into wordpress plugin repository?
That's something that I can remove from my list of fixes
https://github.com/pravdomil/wp-fix/commit/52bfabbb95e1731e64a6b7313601eff75c391edb

**Comment by oncletom** [comment]
@pravdomil yeah I just changed laptop and I think I will try to automate pushing changes on master to wordpress svn repo.

**Comment by pravdomil** [comment]
OK, share some tips.
I have all my wp plugins on GitHub and I want to keep them in sync with WordPress repos.
Maybe there is some online tool. It would be great to make it in cloud with no need to setup local computer.

**Pull request merged**
