### PR TITLE
Minify Less output

### PR DESCRIPTION
**Pull request by Pravdomil**

### CODE REVIEW

**Comment by Pravdomil** [comment]
please merge

**Comment by Pravdomil** [comment]
please merge

**Comment by oncletom** [comment]
You can hook on `wp-less_init` and do something like:

```php
add_action('wp-less_init', 'configure_wp_less');

function configure_wp_less($WPLess) {
  $WPLess->compiler->setFormatter('...');
}
```

Otherwise please provide more ample reasons than a pretty much impolite *please merge*.

**Comment by Pravdomil** [comment]
Well I got with your snippet:
cannot access protected property wplessplugin::$compiler

**Comment by oncletom** [comment]
@Pravdomil so instead of `$WPLess->compiler` use the public method `$WPLess->getCompiler()`. I reckon it is not documented but this is something you can look out by browsing the [`Plugin.php`](https://github.com/oncletom/wp-less/blob/master/lib/Plugin.class.php) class.

**Comment by Pravdomil** [comment]
OK, thanks for support.

The last issue, if I switched to oyejorge less compiler and use $WPLess->getCompiler->setFormatter it doesn't work.

In lessc->compileFile function is Less_Parser always loaded with no args so compression cannot be applied. I found workaround for it:

``` php
// turn on compression for oyejorge less compiler
add_action('wp-less_compiler_construct_pre', function($compiler) {
	Less_Parser::$options['compress'] = true;
});
```
I use it here https://github.com/Pravdomil/wp-pravdomil/blob/master/less.php#L26

**Comment by oncletom** [comment]
Well, `setFormatter` exists in oyejorge flavour of wp-less: https://github.com/oyejorge/less.php/blob/master/lessc.inc.php#L38

Your workaround seems legit, it seems to be enabled if the `compressed` formatter is used (cf. https://github.com/oyejorge/less.php/blob/master/lessc.inc.php#L81)

**Comment by Pravdomil** [comment]
I download the latest version from https://wordpress.org/plugins/wp-less/ and it seems that oyejorge library is older then master on Github. Comparing compileFile function.

wp-less/vendor/oyejorge/less.php/lessc.inc.php: 127
``` php
$parser = new Less_Parser();
$parser->SetImportDirs($this->getImportDirs());
if( count( $this->registeredVars ) ) $parser->ModifyVars( $this->registeredVars );
$parser->parseFile($fname);
$out = $parser->getCss();
```

https://github.com/oyejorge/less.php/blob/master/lessc.inc.php#L141
``` php
$parser = new Less_Parser($this->getOptions());
$parser->SetImportDirs($this->getImportDirs());
if( count( $this->registeredVars ) ) $parser->ModifyVars( $this->registeredVars );
foreach ($this->libFunctions as $name => $func) {
	$parser->registerFunction($name, $func);
}
$parser->parseFile($fname);
$out = $parser->getCss();
```
I'm right?

**Comment by oncletom** [comment]
Yep you are right. Bundled versions were out of date, released as `v1.7.6`. Give it a try and let us know :-)

**Comment by Pravdomil** [comment]
I think that it will work, can you please update the oyejorge compiler? Can I help you some how?

After that, we can use this snippet for compressed output:
```php
add_filter('wp_less_compiler', function() { return 'less.php'; } );

add_action('wp-less_init', function($WPLess) {
  $WPLess->getCompiler()->setFormatter('compressed');
} );
```

**Comment by oncletom** [comment]
@Pravdomil I updated both of them (leafo/lessphp bumped from `0.4` to `0.5`). Cf. https://plugins.trac.wordpress.org/changeset/1241501/wp-less#file1

**Comment by Pravdomil** [comment]
Great, now the compression works perfectly with both compilers.

I would recommend to use oyejorge library since it's official php less compiler and more up to date, what do you think?

**Comment by oncletom** [comment]
It would be just a matter of changing the default value for the filter (to `less.php`): https://github.com/oncletom/wp-less/blob/master/lib/Plugin.class.php#L68

Feel free to open a PR for this :-)

**Comment by Pravdomil** [comment]
https://github.com/oncletom/wp-less/pull/90

**Pull request closed without merging**
